 <div>
            <p>This is the filters</p>
            <ul>
                <li>
                    <p>Technologies</p>
                    <button>JavaScript</button>
                    <button>Sass</button>
                    <button>MySQL</button>
                    <button>Java</button>
                    <button>MongoDB</button>
                    <button>React</button>
                    <button>Node.js</button>
                    <button>Python</button>
                    <button>Angular</button>
                    <button>C++</button>
                </li>
                <li>
                    <p>Industry</p>
                    <button>IT</button>
                    <button>Hospitality</button>
                   <button>Automotive</button>
                    <button>Textile</button>
                    <button>ECommerce</button>
                    <button>Food</button>
                </li>
                <li>
                    <p>Location</p>
                    <button>Paris</button>
                    <button>Nantes</button>
                    <button>Montpeller</button>
                    <button>Casablanca</button>
                    <button>Munich</button>
                    <button>Rennes</button>
                    <button>Lille</button>
                    <button>Brest</button>
                    <button>Bruxelles</button>
                    <button>Aveiro</button>
                    <button>Dijon</button>
                    <button>Toulouse</button>
                </li>
                <li>
                    <p>Status</p>
                    <button>Beginning</button>
                    <button>Middle</button>
                    <button>End</button>
                    <button>Overdue</button>
                </li>
                <li>
                    <p>Team Vacancies</p>
                    <button>Open</button>
                    <button>Full</button>
                </li>
                <li>
                    <p>Popularity</p>
                    <button>Highest</button>
                    <button>Lowest</button>
                </li>
            </ul>
        </div>